name: Auto approve revert PR

on: pull_request_target

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: startsWith(github.event.pull_request.title, 'Revert') && !startsWith(github.event.pull_request.title, 'Revert "Revert')
    steps:
      # checkout the repository
      - uses: actions/checkout@v3

      # run privileged-requester
      - uses: github/privileged-requester@v1.0.0
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
          robotUserToken: ${{ secrets.REPO_GITHUB_TOKEN }}
          path: config/privileged-requester.yaml
          prCreator: ${{ github.event.pull_request.user.login }}
          prNumber: ${{ github.event.pull_request.number }}
          checkCommits: "true"
          checkDiff: "true"
          checkLabels: "true"