name: Auto approve revert PR

on: pull_request_target

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: startsWith(github.event.pull_request.title, 'Revert')
    steps:
      - uses: hmarr/auto-approve-action@v3